config/routes.rb
Rails.application.routes.draw do

  # Create
  get 'pets/new', to: 'pets#new'
  post 'pets', to: 'pets#create'

  # Read
  get 'pets/:id', to: 'pets#show', as: :pet
  get 'pets', to: 'pets#index'

  # Update
  get 'pets/:id/edit', to: 'pets#edit', as: :pet_edit
  patch 'pets/:id', to: 'pets#update'

  # Delete/Destroy
  delete 'pets/:id', to: 'pets#destroy'

  root to: 'pets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES_ALLOWED = %w[cat dog parrot dinossaur]

  validates :name, :address, :found_on, :species, presence: true
  validates :species, inclusion: { in: SPECIES_ALLOWED }

  def found_days_ago
    days_since_found = (Date.today - found_on).to_i
    "found #{days_since_found} days ago"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %w[show edit update destroy]

  def index
    @pets = Pet.all
  end

  def show; end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to @pet
    # redirect_to pet_path(@pet)
    # redirect_to pet_path(@pet.id)
  end

  def edit; end

  def update
    @pet.update(pet_params)
    redirect_to @pet
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_for pet do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </p>
  <p>
    <%= form.label :species %>
    <%= form.select :species, Pet::SPECIES_ALLOWED %>
  </p>
  <p>
    <%= form.label :found_on %>
    <%= form.text_field :found_on %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit found pet</h1>
<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<h1>Found missing animals, that were also lost</h1>
<%= link_to 'New found pet', pets_new_path %>
<ul>
  <% @pets.each do |pet| %>
    <li>
      <p><%= link_to pet.name, pet %></p>
      <%#= link_to pet.name, pet_path(pet) %>
      <%#= link_to pet.name, pet_path(pet.id) %>
      <p><%= pet.species %></p>
      <p><%= pet.address %></p>
      <p><%= pet.found_days_ago %></p>
    </li>
  <% end %>
</ul>

app/views/pets/new.html.erb
<h1>Add found pet</h1>
<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<p><%= @pet.species %></p>
<p><%= @pet.address %></p>
<p><%= @pet.found_days_ago %></p>
<%= link_to 'Edit', pet_edit_path(@pet) %>
<%= link_to 'Delete', @pet, method: :delete %>
<%#= link_to 'Delete', pet_path(@pet) %>
<%#= link_to 'Delete', pet_path(@pet.id) %>
<%= link_to 'Back to list', pets_path %>